<?php

namespace App\Filament\Resources\AccountingExports\Schemas;

use App\Models\AccountingExport;
use App\Support\Money;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class AccountingExportInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema->components([
            Section::make('Export summary')
                ->description('An immutable record of the journals included in this Peachtree workbook.')
                ->schema([
                    Grid::make(3)->schema([
                        TextEntry::make('status')->badge(),
                        TextEntry::make('cutoff_at')->dateTime('M j, Y H:i T'),
                        TextEntry::make('generated_at')->dateTime('M j, Y H:i T')->placeholder('Not generated'),
                        TextEntry::make('journal_count')->numeric(),
                        TextEntry::make('row_count')->label('Journal lines')->numeric(),
                        TextEntry::make('generatedBy.name')->label('Generated by')->placeholder('Scheduler'),
                        TextEntry::make('total_debit')->formatStateUsing(fn ($state): string => Money::format($state)),
                        TextEntry::make('total_credit')->formatStateUsing(fn ($state): string => Money::format($state)),
                        TextEntry::make('file_name')->placeholder('No file created'),
                    ]),
                ]),
            Section::make('Failure details')
                ->icon('heroicon-o-exclamation-triangle')
                ->schema([
                    TextEntry::make('error_message')->label('What needs attention'),
                ])
                ->visible(fn (AccountingExport $record): bool => $record->status === AccountingExport::STATUS_FAILED),
            Section::make('Audit details')
                ->collapsed()
                ->schema([
                    TextEntry::make('checksum')->label('SHA-256 checksum')->copyable(),
                    TextEntry::make('file_path')->label('Private storage path'),
                ])
                ->visible(fn (AccountingExport $record): bool => $record->status === AccountingExport::STATUS_COMPLETED),
        ]);
    }
}
